
name: tests 

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Mon
      DEBUG: ${{ secrets.DEBUG }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SQLALCHEMY_DATABASE_URI: sqlite:///data-dev.sqlite3
      DEFAULT_VOCABULARY_URL: ${{ secrets.DEFAULT_VOCABULARY_URL }}

    steps:
    - name: Get the source code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install -r requirements.txt
        pip install -e .

    - name: Download spacy dictionaries
      run: |
         python -m spacy download en_core_web_sm

    - name: Test environment variables
      run: |
          echo "This is the debug ${{ secrets.DEBUG }} variable."
          echo "This is the debug ${{ secrets.SECRET_KEY }} variable."
          echo "This is the debug ${{ secrets.SQLALCHEMY_DATABASE_URI }} variable."
          echo "This is the debug ${{ secrets.DEFAULT_VOCABULARY_URL }} variable."

    - name: Test
      run: |
        pytest

    - name: Lint
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=79 --statistics
